//package com.benetech.demo.drools.domain

import com.benetech.demo.drools.domain.Message
//import org.slf4j.Logger
//import org.slf4j.LoggerFactory

dialect  "mvel"

rule "Hello World"
    dialect "mvel"
    when
        m : Message(status.equals(Message.HELLO), message : message )
    then
        System.out.println( message);
    modify ( m ) { message = "Goodbye cruel world",status = Message.GOODBYE };
end

rule "Good Bye"
    dialect "java"
    when
       Message( status == Message.GOODBYE, message : message )
    then
       System.out.println(message+" From Jz test");
end