package rules;
dialect  "mvel"

import com.benetech.demo.drools.domain.testquery.Person

rule "RuleA"
salience 95
when
    $person : Person( age < 21 )
then
    System.out.println("RuleA : " + $person);
    update($person);
end

rule "RuleB"
salience 100
when
   $person : Person( age < 21 )
then
   $person.setName("David");
   $person.setAge(30);
   System.out.println("RuleB : " + $person);
   update($person);
end
